environment:
  matrix:
    - PY: "3.6"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz/label/dev pyctdev && doit ecosystem_setup"
  - "conda config --set always_yes True"
  - "conda create -n earthsim -c pyviz/label/earthsim -c conda-forge --file=dependencies.txt conda-forge::python=3.6"
  - "activate earthsim"
  - "pip install -e . --no-deps"
  - "doit env_capture"

build: off

test_script:
  - "earthsim fetch-data --path=examples"
  - "doit test_all"
