name: earthsim
channels:
    - pyviz/label/dev
    - ceball    
    - conda-forge
    - defaults
    - erdc
dependencies:

    ########### direct deps
    - conda-forge::python=3.6
    - conda-forge::fiona
    - conda-forge::gdal
    - conda-forge::cartopy
    - conda-forge::bokeh
    - conda-forge::xarray
    - conda-forge::geopandas
    - conda-forge::jupyter
    - conda-forge::opencv
    - conda-forge::gsshapy
    ####
    # Should move updated packaging to erdc when done, and when source
    # is public should be moved to conda-forge
    - ceball::gssha=7.12.2+ceball
    # (lib)filigree still WIP
    - ceball::filigree=0.0.6+ceball
    - ceball::libfiligree=0.0.4+ceball
    ####

    - erdc::quest
    - pyviz/label/dev::datashader
    - pyviz/label/dev::param
    - pyviz/label/dev::parambokeh
    - pyviz/label/dev::paramnb
#    - pyviz/label/dev::geoviews
#    - conda-forge::lancet

    # won't necessarily need all these with pinning now working...

    ########### indirect deps
    #
#    - conda-forge::libgdal    
    - pyviz/label/dev::pyviz_comms  # missing from parambokeh
    - conda-forge::scikit-image     # ?
    - conda-forge::descartes        # ?
    - conda-forge::numpy            # ensure scipy (and hence its deps) come from c-f
    - conda-forge::scipy            #
#    - conda-forge::libgfortran      # (also for scipy)

    ########### for tests
    - pyviz/label/dev::nbsmoke

    - pip:
        - git+https://github.com/ioam/holoviews.git
        - git+https://github.com/ioam/geoviews.git
