name: earthsim
channels:
    - pyviz/label/dev
    - ceball
    - conda-forge
    - defaults
    - erdc
dependencies:

    ########### direct deps
    - conda-forge::python>=3.5
    - conda-forge::fiona
    - conda-forge::gdal
    - conda-forge::cartopy
    - conda-forge::bokeh
    - conda-forge::xarray
    - conda-forge::geopandas
    - conda-forge::jupyter
    - conda-forge::filigree
    - ioam::lancet
    - conda-forge::opencv
    - pyviz/label/dev::datashader
    - pyviz/label/dev::param
    - pyviz/label/dev::parambokeh
    - pyviz/label/dev::paramnb

    - conda-forge::gsshapy
    - ceball::gssha

    ########### indirect deps
    #
    - conda-forge::rasterio         # quest
    - conda-forge::ulmo>=0.8.3.2    # quest
    - conda-forge::pyyaml           # quest
    - conda-forge::matplotlib       # quest
    - conda-forge::click            # quest
    - conda-forge::werkzeug         # quest
    - conda-forge::peewee           # quest
    - conda-forge::psutil           # quest
    - conda-forge::pint             # quest
    - conda-forge::pony             # quest
    - conda-forge::pytest-cov       # quest
    - conda-forge::stevedore        # quest
    - pyviz/label/dev::pyviz_comms  # missing from parambokeh
    - conda-forge::scikit-image     # ?
    - conda-forge::go-spatial       # ?
    - conda-forge::descartes        # ?
    - conda-forge::json-rpc         # ?
    - conda-forge::numpy=1.13       # avoid warnings with numpy=1.14 and bokeh=1.12.14
    - conda-forge::scipy            # ensure scipy (and hence its deps) come from c-f
    - conda-forge::libgfortran      # (also for scipy)

    ########### for tests
    - pyviz/label/dev::nbsmoke

    - pip:
        - git+https://github.com/ioam/holoviews.git
        - git+https://github.com/ioam/geoviews.git
        - git+https://github.com/erdc/quest.git
