name: earthsim
channels:
    - pyviz/label/dev
    - ioam
    - bokeh
    - conda-forge
    - erdc    
    - defaults
dependencies:
    - python=3.5
    - fiona
    - rasterio
    - gdal
    - json-rpc
    - ulmo>=0.8.3.2
    - pyyaml
    - matplotlib
    - click
    - werkzeug
    - peewee
    - geopandas
    - psutil
    - pint
    - pony
    - scikit-image
    - go-spatial
    - jupyter
    - descartes
    - gsshapy
    - cartopy
    - bokeh
    - xarray
    - gssha
    - datashader
    - filigree
    - param
    - parambokeh
    - paramnb
    ### dependencies for tests
    - nbsmoke
    - pytest-cov
    ### dependencies for pip installed packages
    # for quest
    - stevedore

    - pip:
        - git+https://github.com/ioam/holoviews.git
        - git+https://github.com/ioam/geoviews.git
        - git+https://github.com/erdc/quest.git
